namespace DotNetFaker.Common
{
    public static  class Constants
    {

        private static readonly string[] addresses = {
            "43 Framley Rd, Tonbridge TN10 4HT, Reino Unido",
            "57 Highfield Gardensprivate static readonly Grays RM16 2NT, Reino Unido",
            "85 School Ln, Hartford, Northwich CW8 1PW, Reino Unido",
            "17 Pentland Grove, Darlington DL3 8BA, Reino Unido",
            "1 Carlton Pl, Teignmouth TQ14, Reino Unido",
            "16 Hill St, Arbroath DD11 1AA, Reino Unido",
            "40 N Seaton Rd, Newbiggin-by-the-Sea NE64 6XT, Reino Unido",
            "A48, Westbury-on-Severn GL14 1QR, Reino Unido",
            "4 Lakeside, Cwmtillery, Abertillery NP13 1LS, Reino Unido",
            "12 Marina View, Thorne, Doncaster DN8 5TS, Reino Unido",
            "124 Commercial Rd, Bournemouth BH2 5AT, Reino Unido",
            "14 Fergus Dr, Lewiston, Drumnadrochit, Inverness IV63 6UW, Reino Unido",
            "Laverstoke Ln, Whitchurch RG28, Reino Unido",
            "5 Ardmeanach View, Bunessan, Isle of Mull PA67 6DA, Reino Unido",
            "16 Kildare Rd, Nottingham NG3 3AF, Reino Unido",
            "8 Rabbits Rd, London E12 5HZ, Reino Unido",
            "18 Beddington Cross, Croydon CR0, Reino Unido",
            "13 Coode Way, Portland DT5, Reino Unido",
            "4 Lighthouse Rd, Lizard, Helston TR12 7NT, Reino Unido",
            "18 Airdrie Rd, Cumbernauld, Glasgow G67 4DN, Reino Unido",
            "4 Ingleston Cres, New Abbey, Dumfries DG2 8DD, Reino Unido",
            "5 Milton Terrace, Grange-over-Sands LA11 6AG, Reino Unido",
            "9 Camel Cl, Padstow PL28 8EJ, Reino Unido",
            "17 Clyde St, Millport, Isle of Cumbrae KA28 0EP, Reino Unido",
            "4 Beech Walk, Jedburgh TD8 6JE, Reino Unido",
            "18 Capon Tree Rd, Brampton CA8, Reino Unido",
            "5 Mount View, Colyton EX24 6RH, Reino Unido",
            "67 Mill Ln, Hazel Grove, Stockport SK7 6DW, Reino Unido",
            "1 Station Rd, Shipley BD18 2JL, Reino Unido",
            "11 Westfield Cl, Hotham, York YO43 4UE, Reino Unido",
            "3 Pitnamoon Cottages, Laurencekirk AB30 1ES, Reino Unido",
            "3 The Mallards, Fareham PO16 7XR, Reino Unido",
            "St John's Rd, Yeadon, Leeds LS19 7LY, Reino Unido",
            "5 Kilmaurs Rd, Crosshouse, Kilmarnock KA2 0HL, Reino Unido",
            "1 Humphreys Terrace, Maesteg CF34 0SG, Reino Unido",
            "27 Starling Rd, Radcliffe, Manchester M26 4LW, Reino Unido",
            "1 Ravenshoe Cl, Wooburn Green, Bourne End SL8 5QP, Reino Unido",
            "112 Connaught Rd, Brookwood, Woking GU24 0AR, Reino Unido",
            "9 Wearfield, Sunderland SR5 2TG, Reino Unido",
            "10 High St, Huddersfield HD1 4SJ, Reino Unido",
            "12 Herne Hill, London SE24 9LX, Reino Unido",
            "152-160 Whatriggs Rd, Kilmarnock KA1 3TE, Reino Unido"
        };

        private static readonly string[] companies = {
            "AT&T",
            "Cartier SA",
            "Yahoo!",
            "Intel Corporation",
            "Burberry",
            "L'Oréal",
            "Pampers",
            "Credit Suisse",
            "Ferrari S.p.A.",
            "Kia Motors",
            "Tiffany & Co.",
            "Avon",
            "Verizon Communications",
            "Jack Daniel's",
            "Louis Vuitton",
            "Panasonic Corporation",
            "MasterCard",
            "Canon",
            "Starbucks",
            "Caterpillar Inc.",
            "Nintendo",
            "American Express",
            "Hermès",
            "Global Gillette",
            "Corona",
            "Gucci",
            "The Walt Disney Company",
            "Moët et Chandon",
            "Nokia",
            "Xerox",
            "Wal-Mart",
            "BMW",
            "Morgan Stanley",
            "Kleenex",
            "Gap Inc.",
            "Toyota Motor Corporation",
            "Amazon.com",
            "Honda Motor Company, Ltd",
            "Porsche",
            "Tesco Corporation",
            "Mercedes-Benz",
            "Google",
            "Nissan Motor Co., Ltd.",
            "Wells Fargo",
            "United Parcel Service",
            "Nike, Inc.",
            "Microsoft",
            "Chase",
            "MTV",
            "Sprite",
            "Samsung Group",
            "eBay",
            "Home Depot",
            "Bank of America",
            "NTT Data",
            "Siemens AG",
            "Adidas",
            "IBM",
            "General Electric",
            "SAP",
            "Nescafé",
            "H&M",
            "Johnson & Johnson",
            "Kellogg Company",
            "Beko",
            "Apple Inc.",
            "Pizza Hut",
            "Deere & Company",
            "PepsiCo",
            "Facebook, Inc.",
            "Allianz",
            "3M",
            "Oracle Corporation",
            "Citigroup",
            "Harley-Davidson Motor Company",
            "Sony",
            "Hewlett-Packard",
            "VISA",
            "Shell Oil Company",
            "KFC",
            "Prada",
            "HSBC",
            "Budweiser Stag Brewing Company",
            "Adobe Systems",
            "Ralph Lauren Corporation",
            "BlackBerry",
            "Cisco Systems, Inc.",
            "Smirnoff",
            "Mitsubishi",
            "McDonald's",
            "Zara",
            "Coca-Cola",
            "Audi",
            "IKEA",
            "Johnnie Walker",
            "Vodafone",
            "Heineken Brewery",
            "Hyundai",
            "Volkswagen Group"
        };

        private static readonly string[] personNames = {
            "Merrill Bustos",
            "Humberto Hust",
            "Jim Butner",
            "Clair Sharp",
            "Jacques Lubbers",
            "Lesley Oconner",
            "Dwayne Shawver",
            "Robbie Glessner",
            "Rogelio Savidge",
            "Jimmy Royal",
            "Guillermo Conatser",
            "Adrian Griggs",
            "Jack Strassburg",
            "Caleb Mcinturff",
            "Sanford Weich",
            "Genaro Sergent",
            "Donn Phegley",
            "Charley Emigh",
            "Benton Carbo",
            "Brooks Cauble",
            "Sydney Cully",
            "Nolan Kretschmer",
            "Bob Schempp",
            "Wiley Mcenaney",
            "Danilo Casavant",
            "Bruno Mccall",
            "Michal Bohanan",
            "Geraldo Borrero",
            "Charlie Crupi",
            "Brendon Zane",
            "Emmett Thatch",
            "Leonard Watwood",
            "Noah Pressly",
            "Wilford Capello",
            "Franklin Wann",
            "Kory Norred",
            "Alex Torrain",
            "Abraham Henrikson",
            "Ollie Virden",
            "Raymundo Peeples",
            "Mohammad Corl",
            "Stan Huizar",
            "Clyde Kautz",
            "Alfredo Layton",
            "Reed Burcham",
            "Wesley Nazzaro",
            "Mickey Rubi",
            "Earl Heslin",
            "Sol Holahan",
            "Russ Jarnagin",
            "Daniella Farkas",
            "Rebekah Delph",
            "Alfredia Tapper",
            "Lavette Kirkley",
            "Herta Rattler",
            "Thea Verne",
            "Sina Bohman",
            "Arlena Cureton",
            "Alysa Kotek",
            "Lala Adcox",
            "Genevive Felice",
            "Lucia Mejias",
            "Hortensia Sharp",
            "Alissa Farrier",
            "Lashay Godines",
            "Lanelle Begley",
            "Bebe Cobbley",
            "Loralee Turnbow",
            "Renea Kuehne",
            "Tasia Florey",
            "Eden Hanley",
            "Suzy Moats",
            "Trula Mollica",
            "Sachiko Thibodeau",
            "Simonne Yonts",
            "Estell Guttman",
            "Cherlyn Hillenbrand",
            "Joycelyn Olden",
            "Maddie Rankins",
            "Keli Trask",
            "Soo Rhinehart",
            "Katerine Eady",
            "Jade Dunford",
            "Illa Mcamis",
            "Wendolyn Drakeford",
            "Jada Hardman",
            "Sharyn Merida",
            "Dortha Newsome",
            "Ammie Gowans",
            "Chun Fick",
            "Ena Carn",
            "Heide Hartshorn",
            "Jill Mcelligott",
            "Diedre Ehle",
            "Kindra Brigham",
            "Elenora Bigley",
            "Cythia Guimond",
            "Leora Stamant",
            "Jovita Sproles",
            "Tajuana Funk  "
        };


        public static string[] Addresses => addresses;

        public static string[] Companies => companies;

        public static string[] PersonNames => personNames;
    }
}
